[package]
name = "vsockproxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vsock = "0.4.0"
libc = "0.2"

[dev-dependencies]
assert_cmd = "2.0.13"
predicates = "3.1.0"